---
apiVersion: v1
kind: ReplicationController
metadata:
  name: vault-slave
  namespace: vault
  labels:
    name: vault-slave
spec:
  replicas: 1
  selector:
    name: vault-slave
  template:
    metadata:
      labels:
        name: vault-slave
        role: vault
    spec:
      containers:
      - name: vault
        image: quay.io/ukhomeofficedigital/hod-vault:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        env:
        - name: KUBE_CONFIG
          value: /etc/vault/kubeconfig
        - name: KUBE_NAMESPACE
          value: vault
        - name: VAULT_DEFAULT_PASSWORD_FILE
          value: /etc/vault/vault.admin
        - name: VAULT_CONFIG
          value: /etc/vault/vault.hcl
        - name: VAULT_ROLLBACK
          value: "0"
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-unseal
          mountPath: /etc/secrets
        - name: vault-certs
          mountPath: /etc/certs
      volumes:
      - name: vault-config
        secret:
          secretName: vault-config
      - name: vault-certs
        secret:
          secretName: vault-certs
      - name: vault-unseal
        secret:
          secretName: vault-unseal
