---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    name: vault
  namespace: vault
spec:
  type: ClusterIP
  clusterIP: 10.200.10.10
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
  selector:
    role: vault
