---
apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    backend "dynamodb" {
      table =

      add
    }
    listener "tcp" {
      address = "127.0.0.1:8200"
      tls_cert_file = "/etc/ssl/vault/vault-crt.pem"
      tls_key_file = "/etc/ssl/vault/vault-key.pem"
    }
    disable_mlock = true
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal
  namespace: vault
data:
  vault-unseal.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  namespace: vault
data:
  kubeconfig.yml: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://10.200.0.1
      name: default
    contexts:
    - context:
        user: vault
        cluster: default
      name: default
    current-context: default
    users:
    - name: vault
      user:
        token:
